name: Generate Baidu Token

on:
  push:
    branches: [ master ]
  schedule:
    # At 00:00 on day-of-month 1 in every 3rd month.
    - cron:  '0 0 1 */3 *'

jobs:
  generate_baidu_token:
    name: Generate baidu token
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Init
      run: npm i
    - name: Link to Vercel
      env: 
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel link --confirm -t $VERCEL_TOKEN

    - name: Delete old Baidu Token
      env: 
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: echo 'y' | npx vercel env rm VITE_APP_BAIDU_KEY -t $VERCEL_TOKEN > /dev/null

    - name: Generate new Baidu Token and update
      env:
        VITE_BAIDU_API_KEY: ${{ secrets.VITE_BAIDU_API_KEY }}
        VITE_BAIDU_SECRET_KEY: ${{ secrets.VITE_BAIDU_SECRET_KEY }}
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: node ./updateToken.js | npx vercel env add VITE_APP_BAIDU_KEY production -t $VERCEL_TOKEN
      
    - name: Deploy
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: npx vercel --prod -t $VERCEL_TOKEN
